import { UEditorConfig } from '.';

export default <UEditorConfig>{
  // serverUrl: '',
  imageActionName: 'uploadimage',
  scrawlActionName: 'uploadscrawl',
  videoActionName: 'uploadvideo',
  fileActionName: 'uploadfile',
  imageFieldName: 'file',
  imageMaxSize: 5242880,
  imageUrlPrefix: '',
  scrawlUrlPrefix: '',
  videoUrlPrefix: '',
  fileUrlPrefix: '',
  catcherLocalDomain: '',

  zIndex: 1100,
  autoHeightEnabled: false,
  xssFilterRules: true,
  inputXssFilter: true,
  outputXssFilter: true,
  toolbars: [
    [
      'fullscreen',
      'source',
      '|',
      'undo',
      'redo',
      '|',
      'bold',
      'italic',
      'underline',
      'fontborder',
      'strikethrough',
      'superscript',
      'subscript',
      'removeformat',
      'formatmatch',
      'autotypeset',
      'blockquote',
      'pasteplain',
      '|',
      'forecolor',
      'backcolor',
      'insertorderedlist',
      'insertunorderedlist',
      'selectall',
      'cleardoc',
      '|',
      'rowspacingtop',
      'rowspacingbottom',
      'lineheight',
      '|',
      'customstyle',
      'paragraph',
      'fontfamily',
      'fontsize',
      '|',
      'directionalityltr',
      'directionalityrtl',
      'indent',
      '|',
      'justifyleft',
      'justifycenter',
      'justifyright',
      'justifyjustify',
      '|',
      'touppercase',
      'tolowercase',
      '|',
      'link',
      'unlink',
      'anchor',
      '|',
      'imagenone',
      'imageleft',
      'imageright',
      'imagecenter',
      '|',
      // 'simpleupload',
      'insertimage',
      'emotion',
      'scrawl',
      'insertvideo',
      'music',
      'attachment',
      'map',
      'gmap',
      'insertframe',
      // 'webapp',
      'pagebreak',
      'template',
      'background',
      '|',
      'insertcode',
      'horizontal',
      'date',
      'time',
      'spechars',
      'snapscreen',
      'wordimage',
      '|',
      'inserttable',
      'deletetable',
      'insertparagraphbeforetable',
      'insertrow',
      'deleterow',
      'insertcol',
      'deletecol',
      'mergecells',
      'mergeright',
      'mergedown',
      'splittocells',
      'splittorows',
      'splittocols',
      'charts',
      '|',
      'print',
      'preview',
      'searchreplace',
      'drafts',
      'help'
    ]
  ],
  whiteList: {
    a: ['target', 'href', 'title', 'class', 'style'],
    abbr: ['title', 'class', 'style'],
    address: ['class', 'style'],
    area: ['shape', 'coords', 'href', 'alt'],
    article: [],
    aside: [],
    audio: ['autoplay', 'controls', 'loop', 'preload', 'src', 'class', 'style'],
    b: ['class', 'style'],
    bdi: ['dir'],
    bdo: ['dir'],
    big: [],
    blockquote: ['cite', 'class', 'style'],
    br: [],
    caption: ['class', 'style'],
    center: [],
    cite: [],
    code: ['class', 'style'],
    col: ['align', 'valign', 'span', 'width', 'class', 'style'],
    colgroup: ['align', 'valign', 'span', 'width', 'class', 'style'],
    dd: ['class', 'style'],
    del: ['datetime'],
    details: ['open'],
    div: ['class', 'style'],
    dl: ['class', 'style'],
    dt: ['class', 'style'],
    em: ['class', 'style'],
    font: ['color', 'size', 'face'],
    footer: [],
    h1: ['class', 'style'],
    h2: ['class', 'style'],
    h3: ['class', 'style'],
    h4: ['class', 'style'],
    h5: ['class', 'style'],
    h6: ['class', 'style'],
    header: [],
    hr: [],
    i: ['class', 'style'],
    img: ['src', 'alt', 'title', 'width', 'height', 'id', '_src', '_url', 'loadingclass', 'class', 'data-latex'],
    ins: ['datetime'],
    li: ['class', 'style'],
    mark: [],
    nav: [],
    ol: ['class', 'style'],
    p: ['class', 'style'],
    pre: ['class', 'style'],
    s: [],
    section: [],
    small: [],
    span: ['class', 'style'],
    sub: ['class', 'style'],
    sup: ['class', 'style'],
    strong: ['class', 'style'],
    table: ['width', 'border', 'align', 'valign', 'class', 'style'],
    tbody: ['align', 'valign', 'class', 'style'],
    td: ['width', 'rowspan', 'colspan', 'align', 'valign', 'class', 'style'],
    tfoot: ['align', 'valign', 'class', 'style'],
    th: ['width', 'rowspan', 'colspan', 'align', 'valign', 'class', 'style'],
    thead: ['align', 'valign', 'class', 'style'],
    tr: ['rowspan', 'align', 'valign', 'class', 'style'],
    tt: [],
    u: [],
    ul: ['class', 'style'],
    video: ['autoplay', 'controls', 'loop', 'preload', 'src', 'height', 'width', 'class', 'style'],
    source: ['src', 'type'],
    embed: ['type', 'class', 'pluginspage', 'src', 'width', 'height', 'align', 'style', 'wmode', 'play', 'autoplay', 'loop', 'menu', 'allowscriptaccess', 'allowfullscreen', 'controls', 'preload'],
    iframe: ['src', 'class', 'height', 'width', 'max-width', 'max-height', 'align', 'frameborder', 'allowfullscreen']
  }
};
